NPL-6009-circular dependencies in the batik library
These artifacts were compiled incorrectly, under java 8.

Exporting the map on release/prep produced:

java.lang.UnsupportedClassVersionError: org/apache/batik/util/XMLResourceDescriptor : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.7.0_65]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[na:1.7.0_65]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.7.0_65]
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[na:1.7.0_65]
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[na:1.7.0_65]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.7.0_65]

Deleting these artifacts - in the future, artifacts need to be compiled under java 6, 7, unless the java target version is set.

The artifacts will also be removed from the nexus server.